request-collector:
  annotations:
    notifications.argoproj.io/subscribe.on-sync-running.requestcollector: ""
    notifications.argoproj.io/subscribe.on-sync-succeeded.requestcollector: ""
  replicaCount: 2
  image:
    repository: rgroensfeld/request-collector
    tag: latest
  network:
    http:
      servicePort: 8080
      ingress:
        host: request-collector.apps.okd.baloise.dev

